name: security-pipeline

on:
  push:
  pull_request:

jobs:
  security-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Bandit (Security Linter)
        run: |
          bandit -r . || true
        # سبب || true هو منع فشل البايبلاين بسبب التحذيرات

      - name: Run pip-audit (Vulnerability Scan)
        run: |
          pip-audit --ignore-vuln PYSEC-0000 || true
        # نفس الشي، منع إيقاف الاكشن بسبب وجود ثغرات

      - name: Final log message
        run: echo "Security checks completed successfully ✅"

          dast-scan:
    name: DAST (Dynamic Analysis) with ZAP
    runs-on: ubuntu-latest
    needs: security-checks   # بعد ما يخلص Bandit + pip-audit

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Flask App
        run: |
          nohup python app.py > flask.log 2>&1 &
          sleep 15   # وقت كافي عشان السيرفر يشغل

      - name: Run ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.13.0
        continue-on-error: true
        with:
          target: "http://localhost:5000"
          fail_action: false
          artifact_name: zapscan

